# Generated by Django 5.2.7 on 2025-12-02 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
