# Generated by Django 5.2.7 on 2025-12-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_options_remove_patient_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrequest',
            name='blood_group',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
